### ISSUE TITLE
Error: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager"

### ISSUE THREAD

**Issue by DatHoang95** [loup-v/beacons#38]
E/AndroidRuntime(25157): FATAL EXCEPTION: main
E/AndroidRuntime(25157): Process: com.flutterbeaconexample, PID: 25157
E/AndroidRuntime(25157): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
E/AndroidRuntime(25157): 	at org.altbeacon.beacon.BeaconLocalBroadcastProcessor.unregister(BeaconLocalBroadcastProcessor.java:82)
E/AndroidRuntime(25157): 	at org.altbeacon.beacon.BeaconLocalBroadcastProcessor.register(BeaconLocalBroadcastProcessor.java:74)
E/AndroidRuntime(25157): 	at org.altbeacon.beacon.service.BeaconService.ensureNotificationProcessorSetup(BeaconService.java:257)
E/AndroidRuntime(25157): 	at org.altbeacon.beacon.service.BeaconService.onCreate(BeaconService.java:219)
E/AndroidRuntime(25157): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3534)
E/AndroidRuntime(25157): 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
E/AndroidRuntime(25157): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1732)
E/AndroidRuntime(25157): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25157): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(25157): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/AndroidRuntime(25157): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25157): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
E/AndroidRuntime(25157): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
E/AndroidRuntime(25157): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.flutterbeaconexample-2/base.apk"],nativeLibraryDirectories=[/data/app/com.flutterbeaconexample-2/lib/arm, /data/app/com.flutterbeaconexample-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
E/AndroidRuntime(25157): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(25157): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/AndroidRuntime(25157): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(25157): 	... 13 more
Lost connection to device.

**Comment by DatHoang95** [comment]
Please help me
